/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package runanalyst;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;

public class RunAnalyst {

    public static void main(String[] args) {
        if (args.length > 0) {
            for (String filePath : args) {
                System.out.println("*** Parsing '" + filePath + "' ***");
                File f = new File(filePath);
                if (f.exists()) {
                    GPXParser parser = new GPXParser();
                    try {
                        GPXTrack track = parser.parse(new FileInputStream(f));
                        track.computeTotalDistance();
                        System.out.println("*** Track Information' " + filePath + "' ***");
                        System.out.println(track.printInfo());
                        System.out.println("*** Record Information' " + filePath + "' ***");
                        track.computeRecords();
                        System.out.println(track.printRecords());
                    } catch (FileNotFoundException e) {
                        System.err.println("Reading the file failed: " + e.getMessage());
                        e.printStackTrace();
                    } catch (ParserConfigurationException | SAXException | IOException e) {
                        System.err.println("Parsing the file failed: " + e.getMessage());
                        e.printStackTrace();
                    }
                }
            }
        } else {
            System.err.println("Please, add a file in argument.");
        }
    }
}
